// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectoef;

#nullable disable

namespace projectoef.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20221128001515_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c2a47e1-0a63-41a2-b943-08698f37a827"),
                            Descripcion = "Tareas personales",
                            Nombre = "Personal",
                            Peso = 1
                        },
                        new
                        {
                            Id = new Guid("5281449e-055e-41d6-a0c2-c143a46c73ba"),
                            Descripcion = "Tareas de trabajo",
                            Nombre = "Trabajo",
                            Peso = 2
                        },
                        new
                        {
                            Id = new Guid("8dc08aa0-0bcf-4f97-b44e-99c104f7751d"),
                            Descripcion = "Tareas de estudio",
                            Nombre = "Estudio",
                            Peso = 3
                        });
                });

            modelBuilder.Entity("projectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f25c5b7-8157-4a96-8d92-b23502250980"),
                            CategoriaId = new Guid("6c2a47e1-0a63-41a2-b943-08698f37a827"),
                            Descripcion = "Tarea 1",
                            FechaCreacion = new DateTime(2022, 11, 27, 18, 15, 14, 941, DateTimeKind.Local).AddTicks(1503),
                            Prioridad = 1,
                            Titulo = "Tarea 1"
                        },
                        new
                        {
                            Id = new Guid("3b13c973-8107-4d0f-b85f-0ed1a8e6c87c"),
                            CategoriaId = new Guid("5281449e-055e-41d6-a0c2-c143a46c73ba"),
                            Descripcion = "Tarea 2",
                            FechaCreacion = new DateTime(2022, 11, 27, 18, 15, 14, 941, DateTimeKind.Local).AddTicks(1557),
                            Prioridad = 2,
                            Titulo = "Tarea 2"
                        },
                        new
                        {
                            Id = new Guid("5795f5b2-46d7-4aec-8d90-afafa8e3e96f"),
                            CategoriaId = new Guid("8dc08aa0-0bcf-4f97-b44e-99c104f7751d"),
                            Descripcion = "Tarea 3",
                            FechaCreacion = new DateTime(2022, 11, 27, 18, 15, 14, 941, DateTimeKind.Local).AddTicks(1559),
                            Prioridad = 0,
                            Titulo = "Tarea 3"
                        });
                });

            modelBuilder.Entity("projectoef.Models.Tarea", b =>
                {
                    b.HasOne("projectoef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("projectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
